### ISSUE TITLE
Error Message when deleting a todo with example code

### ISSUE THREAD

**Issue by mbeckenbach** [voznik/ngx-odm#33]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => https://github.com/voznik/ngx-odm/blob/master/CONTRIBUTING.md
[ ] Other... Please describe:
</code></pre>

## Current behavior

When using the removeTodo method from demo an error is thrown. 
Demo does not use this method, copy pasted to new project for testing arround.

```Typescript
removeTodo(todo: Todo) {
    this.todosService.remove(todo.id);
}
```

Document gets deleted but throws this error:
Throws this error: https://github.com/pubkey/rxdb/search?q=DOC11

## Expected behavior
Should delete without error message.

## Minimal reproduction of the problem with instructions

Just add a delete button to a todo item and bind it to the removeTodo Method.

## What is the motivation / use case for changing the behavior?

I would expect that it deletes without an error :-)

## Environment

<pre><code>
Libs:
- @angular/core version: ~10.2.0
- @ngx-odm/rxdb version: ~^2.5.0-alpha

Browser:
- [x] Chrome (desktop) version 90.04...
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

For Tooling issues:
- Node version: 12.13.0
- Platform: Windows

Others:
nope

**Comment by mbeckenbach** [comment]
Forget about it. My mistake. Didn't stop propagation and therefore also called toggle. 

```Typescript
removeTodo(event: Event, todo: Todo): void {
    event.stopPropagation();
    this.todosService.remove(todo.id);
  }
```
